-- =========================================================
-- SUPABASE SETUP — PORTFÓLIO / TRACKING DE VISITAS
-- Rode este arquivo no Supabase em: SQL Editor > New query > Run
-- =========================================================

create table if not exists public.visitas (
  id bigint generated by default as identity primary key,
  ip text,
  cidade text,
  regiao text,
  pais text,
  pais_codigo text,
  latitude double precision,
  longitude double precision,
  dispositivo text,
  navegador text,
  pagina text,
  referrer text,
  visitado_em timestamptz not null default now()
);

alter table public.visitas enable row level security;

-- Limpa políticas antigas com os mesmos nomes, caso você rode o script mais de uma vez.
drop policy if exists "Permitir insert publico de visitas" on public.visitas;
drop policy if exists "Permitir leitura publica das visitas" on public.visitas;

-- Permite que visitantes gravem acessos usando a publishable key.
create policy "Permitir insert publico de visitas"
on public.visitas
for insert
to anon
with check (true);

-- ATENÇÃO: isso deixa a leitura disponível para o painel admin estático funcionar.
-- Para produção real, o ideal é usar Supabase Auth/Edge Function e não expor SELECT público.
create policy "Permitir leitura publica das visitas"
on public.visitas
for select
to anon
using (true);

-- Garante privilégios REST para a role anon.
grant usage on schema public to anon;
grant insert, select on table public.visitas to anon;
grant usage, select on sequence public.visitas_id_seq to anon;
